<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $item = new Product;

        $item->id = 4;
        $item->name = "Đồng hồ Nam Adriatica A8134.5234QF";
        $item->image = "a8134.5234qf-nam-1.jpg";
        $item->price = "4289000";
        $item->quantity = 1;
        $item->status = "Còn hàng";
        $item->supplier = "ABC";
        $item->description = "- Dây đeo làm từ da bò êm nhẹ, mềm mại, ôm sát cổ tay, khung viền thép không gỉ 316L bền bỉ";
        $item->category_id = 1;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 5;
        $item->name = "Đồng hồ Nam Adriatica A8306.5114QF";
        $item->image = "a8306.5114qf-nam-1.jpg";
        $item->price = "4485000";
        $item->quantity = 1;
        $item->status = "Còn hàng";
        $item->supplier = "ABC";
        $item->description = "Dây đeo thép không gỉ cùng khung viền thép không gỉ 316L sang trọng, bền chắc, chống ăn mòn";
        $item->category_id = 1;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 6;
        $item->name = "Đồng hồ Nam Adriatica A8312.5B24Q ";
        $item->image = "a8312.5b24q-nam-1.jpg";
        $item->price = "3605000";
        $item->quantity = 1;
        $item->status = "Hết hàng";
        $item->supplier = "CDF";
        $item->description = "Dây đeo làm từ da bò êm ái, nhẹ nhàng, ôm tay rất tốt, khung viền thép không gỉ 316L bền chắc";
        $item->category_id = 1;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 7;
        $item->name = "Đồng hồ Nam Adriatica A8313.5B54CH";
        $item->image = "adriatica-a83135b54ch-nam-1.jpg";
        $item->price = "4895000";
        $item->quantity = 1;
        $item->status = "Còn hàng";
        $item->supplier = "GLH";
        $item->description = "Hệ số chống nước 5 ATM: Người dùng thoải mái đeo đồng hồ khi tắm, đi mưa, không mang khi bơi, lặn";
        $item->category_id = 1;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 8;
        $item->name = "Đồng hồ Nam Adriatica A1296.5214Q";
        $item->image = "a1296.5214q-nam-1.jpg";
        $item->price = "3667000";
        $item->quantity = 1;
        $item->status = "Còn hàng";
        $item->supplier = "LMN";
        $item->description = "Dây đeo làm từ da bò mềm nhẹ, êm ái, cho cảm giác thoải mái khi mang, khung viền thép không gỉ 316L cứng cáp";
        $item->category_id = 1;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 9;
        $item->name = "Đồng hồ Nam Adriatica A8194.5114Q ";
        $item->image = "a8194.5114q-nam-1.jpg";
        $item->price = "3667000";
        $item->quantity = 1;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Dây đeo thép không gỉ cùng khung viền thép không gỉ 316L có độ bền cao, chống ăn mòn, chống oxy hóa tốt";
        $item->category_id = 1;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 10;
        $item->name = "Đồng hồ Nam Casio AEQ-110W-2AVDF";
        $item->image = "casio-aeq-110w-2avdf-den-1-1-org.jpg";
        $item->price = "828000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Những dòng sản phẩm nổi tiếng của Casio là: G-Shock với thiết kế mạnh mẽ cùng độ bền cao";
        $item->category_id = 2;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 11;
        $item->name = "Đồng hồ Casio AE-1000W-1BVSDF";
        $item->image = "dong-ho-casio-ae-1000w-1bvsdf-nam-1-org.jpg";
        $item->price = "641000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Edifice thiết kế hiện đại cùng nhiều tính năng vượt trội";
        $item->category_id = 2;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 12;
        $item->name = "Đồng hồ Nam Casio MRW-200H-1BVDF";
        $item->image = "casio-mrw-200h-1bvdf-nam-grl-1-org.jpg";
        $item->price = "529000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Sheen với thiết kế cổ điển và sang trọng";
        $item->category_id = 2;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 13;
        $item->name = "Đồng hồ Nam Casio MTP-1215A-1A2DF";
        $item->image = "casio-mtp-1215a-1a2df-nam-5-org.jpg";
        $item->price = "597000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Những dòng sản phẩm nổi tiếng của Casio là: G-Shock với thiết kế mạnh mẽ cùng độ bền cao";
        $item->category_id = 2;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 14;
        $item->name = "Đồng hồ Nam Casio EFR-566PB-1AVUDF";
        $item->image = "casio-efr-566pb-1avudf-nam-1-org.jpg";
        $item->price = "2857000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Những dòng sản phẩm nổi tiếng của Casio là: G-Shock với thiết kế mạnh mẽ cùng độ bền cao";
        $item->category_id = 2;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 15;
        $item->name = "Đồng hồ Nam Casio EFV-610DC-1AVUDF";
        $item->image = "casio-efv-610dc-1avudf-nam-1-org.jpg";
        $item->price = "3063000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "G-Shock với thiết kế mạnh mẽ cùng độ bền cao";
        $item->category_id = 2;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 16;
        $item->name = "Đồng hồ Nam Casio MTP-1375L-1AVDF";
        $item->image = "casio-mtp-1375l-1avdf-nam-grl-1-org.jpg";
        $item->price = "1299000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "G-Shock với thiết kế mạnh mẽ cùng độ bền cao";
        $item->category_id = 2;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 17;
        $item->name = "Đồng hồ Nam Casio MTP-E172D-1AVDF";
        $item->image = "casio-mtp-e172d-1avdf-nam-1-org.jpg";
        $item->price = "1780000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "G-Shock với thiết kế mạnh mẽ cùng độ bền cao";
        $item->category_id = 2;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 18;
        $item->name = "Đồng hồ Nam Bulova 96A187";
        $item->image = "bulova-96a187-nam-1-org.jpg";
        $item->price = "9035000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Thuộc kiểu đồng hồ cơ tự động (máy Automatic) hoạt động bền bỉ không cần pin, nhận năng lượng từ chuyển động của cổ tay";
        $item->category_id = 3;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 19;
        $item->name = "Đồng hồ Nam Bulova 97A161";
        $item->image = "bulova-97a161-nam-1-org.jpg";
        $item->price = "9035000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Thuộc kiểu đồng hồ cơ tự động (máy Automatic) hoạt động bền bỉ không cần pin, nhận năng lượng từ chuyển động của cổ tay";
        $item->category_id = 3;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 20;
        $item->name = "Đồng hồ Nam Bulova 98C127";
        $item->image = "bulova-98c127-nam-1-org.jpg";
        $item->price = "5525000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Thuộc kiểu đồng hồ cơ tự động (máy Automatic) hoạt động bền bỉ không cần pin, nhận năng lượng từ chuyển động của cổ tay";
        $item->category_id = 3;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 21;
        $item->name = "Đồng hồ Nam Bulova 96C125";
        $item->image = "bulova-96c125-nam-1-org.jpg";
        $item->price = "4680000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Thuộc kiểu đồng hồ cơ tự động (máy Automatic) hoạt động bền bỉ không cần pin, nhận năng lượng từ chuyển động của cổ tay";
        $item->category_id = 3;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 22;
        $item->name = "Đồng hồ Nam Bulova 98B301 ";
        $item->image = "bulova-98b301-nam-1-org.jpg";
        $item->price = "9035000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Thuộc kiểu đồng hồ cơ tự động (máy Automatic) hoạt động bền bỉ không cần pin, nhận năng lượng từ chuyển động của cổ tay";
        $item->category_id = 3;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 23;
        $item->name = "Đồng hồ Nam Timex TW2T34700";
        $item->image = "timex-tw2t34700-den8-org.jpg";
        $item->price = "1088000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.";
        $item->category_id = 4;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 24;
        $item->name = "Đồng hồ Nam TimeX TW2R83200";
        $item->image = "timex-tw2r83200-nam-1-1-org.jpg";
        $item->price = "2912000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.";
        $item->category_id = 4;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 25;
        $item->name = "Đồng hồ Nam Timex TW2R88800";
        $item->image = "timex-tw2r88800-nau-4-org.jpg";
        $item->price = "2749000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.";
        $item->category_id = 4;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 26;
        $item->name = "Đồng hồ Nam Timex TW2R38000 ";
        $item->image = "timex-tw2r38000-nam-den-2-org.jpg";
        $item->price = "1492000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.";
        $item->category_id = 4;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 27;
        $item->name = "Đồng hồ Nam Timex TW5M17400";
        $item->image = "timex-tw5m17400-nam-trang-2-org.jpg";
        $item->price = "1100000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Trở thành mẫu đồng hồ đẳng cấp, thời thượng đi kèm chất lượng và bền bỉ theo thời gian.";
        $item->category_id = 4;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 28;
        $item->name = "Đồng hồ Nam Tommy Hilfiger 1791835";
        $item->image = "tommy-1791835-nam-1.jpg";
        $item->price = "2925000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Thương hiệu đồng hồ Tommy nổi tiếng của Mỹ, ấn tượng với phong cách thiết kế năng động, phóng khoáng";
        $item->category_id = 5;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 29;
        $item->name = "Đồng hồ Nam Tommy Hilfiger 1791740 ";
        $item->image = "tommy-1791740-nam-1-org.jpg";
        $item->price = "2535000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Thương hiệu đồng hồ Tommy nổi tiếng của Mỹ, ấn tượng với phong cách thiết kế năng động, phóng khoáng";
        $item->category_id = 5;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 30;
        $item->name = "Đồng hồ Nam Tommy Hilfiger 1791348";
        $item->image = "tommy-1791348-nam-1-org.jpg";
        $item->price = "2925000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Thương hiệu đồng hồ Tommy nổi tiếng của Mỹ, ấn tượng với phong cách thiết kế năng động, phóng khoáng";
        $item->category_id = 5;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 31;
        $item->name = "Đồng hồ Nam Tommy Hilfiger 1791737";
        $item->image = "tommy-1791737-nam-1-org.jpg";
        $item->price = "2730000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Thương hiệu đồng hồ Tommy nổi tiếng của Mỹ, ấn tượng với phong cách thiết kế năng động, phóng khoáng";
        $item->category_id = 5;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 32;
        $item->name = "Đồng hồ Nam Tommy Hilfiger 1791852 ";
        $item->image = "tommy-1791852-nam-1.jpg";
        $item->price = "2730000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Thương hiệu đồng hồ Tommy nổi tiếng của Mỹ, ấn tượng với phong cách thiết kế năng động, phóng khoáng";
        $item->category_id = 5;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 33;
        $item->name = "Đồng hồ Nam Elio ES068-02";
        $item->image = "elio-es068-02-nam-2-org.jpg";
        $item->price = "695000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Sản phẩm đồng hồ mang thương hiệu Elio với nhiều mẫu mã năng động, trẻ trung nhưng không kém phần tinh tế và sang trọng";
        $item->category_id = 6;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 34;
        $item->name = "Đồng hồ Nam Elio ES073-02";
        $item->image = "elio-es073-02-nam-2-2-org.jpg";
        $item->price = "795000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Sản phẩm đồng hồ mang thương hiệu Elio với nhiều mẫu mã năng động, trẻ trung nhưng không kém phần tinh tế và sang trọng";
        $item->category_id = 6;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 35;
        $item->name = "Đồng hồ Nam Elio ES026-C1 ";
        $item->image = "elio-es026-c1-nam-2-org.jpg";
        $item->price = "715000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Sản phẩm đồng hồ mang thương hiệu Elio với nhiều mẫu mã năng động, trẻ trung nhưng không kém phần tinh tế và sang trọng";
        $item->category_id = 6;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 36;
        $item->name = "Đồng hồ Nam Elio ES062-01";
        $item->image = "elio-es062-01-nam-10-org.jpg";
        $item->price = "643000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Sản phẩm đồng hồ mang thương hiệu Elio với nhiều mẫu mã năng động, trẻ trung nhưng không kém phần tinh tế và sang trọng";
        $item->category_id = 6;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 37;
        $item->name = "Đồng hồ Nam Tommy Hilfiger 1791718";
        $item->image = "tommy-1791718-nam-1-org.jpg";
        $item->price = "3120000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Sản phẩm đồng hồ mang thương hiệu Elio với nhiều mẫu mã năng động, trẻ trung nhưng không kém phần tinh tế và sang trọng";
        $item->category_id = 5;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 38;
        $item->name = "Đồng hồ Nam Elio ES067-02";
        $item->image = "elio-es067-02-nam-2-org.jpg";
        $item->price = "838000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Sản phẩm đồng hồ mang thương hiệu Elio với nhiều mẫu mã năng động, trẻ trung nhưng không kém phần tinh tế và sang trọng";
        $item->category_id = 6;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 39;
        $item->name = "Đồng hồ Nam Coach 14602152";
        $item->image = "coach-14602152-nam-1-org.jpg";
        $item->price = "2160000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Một sản phẩm đến từ hãng đồng hồ Coach - Mỹ, nổi tiếng với nhiều chiếc đồng hồ sang trọng, quý phái";
        $item->category_id = 7;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 40;
        $item->name = "Đồng hồ Nam Coach 14602428";
        $item->image = "coach-14602428-nam-1-org.jpg";
        $item->price = "2640000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Một sản phẩm đến từ hãng đồng hồ Coach - Mỹ, nổi tiếng với nhiều chiếc đồng hồ sang trọng, quý phái";
        $item->category_id = 7;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 41;
        $item->name = "Đồng hồ Nam Citizen BI1043-01E ";
        $item->image = "citizen-bi1043-01e-nam-ga-1-org.jpg";
        $item->price = "2040000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Xu hướng thiết kế chính của đồng hồ Citizen là đơn giản và thanh lịch. ";
        $item->category_id = 8;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 42;
        $item->name = "Đồng hồ Nam Citizen BF2020-51E ";
        $item->image = "dong-ho-kim-nam-day-kim-loai-citizen-bf2020-51e-de-ga-1-org.jpg";
        $item->price = "2145000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Xu hướng thiết kế chính của đồng hồ Citizen là đơn giản và thanh lịch. ";
        $item->category_id = 8;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 43;
        $item->name = "Đồng hồ Nam Citizen BM6770-51E - Eco-Drive";
        $item->image = "dong-ho-eco-drive-nam-day-kim-loai-citizen-bm6770-1-1-org.jpg";
        $item->price = "4537000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Xu hướng thiết kế chính của đồng hồ Citizen là đơn giản và thanh lịch. ";
        $item->category_id = 8;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 44;
        $item->name = "Đồng hồ Nam Citizen BI1052-85P";
        $item->image = "dong-ho-nam-citizen-bi1052-85p-vang-1-1-org.jpg";
        $item->price = "2320000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Xu hướng thiết kế chính của đồng hồ Citizen là đơn giản và thanh lịch. ";
        $item->category_id = 8;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 45;
        $item->name = "Đồng hồ Nam Citizen BI5060-51H ";
        $item->image = "dong-ho-nam-citizen-bi5060-51h-trang-1-1-org.jpg";
        $item->price = "2359000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Xu hướng thiết kế chính của đồng hồ Citizen là đơn giản và thanh lịch. ";
        $item->category_id = 8;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 46;
        $item->name = "Đồng hồ Nam Citizen BI5000-10A ";
        $item->image = "dong-ho-kim-nam-day-da-citizen-bi5000-10a-trang-2-org.jpg";
        $item->price = "1950000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Xu hướng thiết kế chính của đồng hồ Citizen là đơn giản và thanh lịch. ";
        $item->category_id = 8;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 47;
        $item->name = "Đồng hồ Nam Obaku V132XCIMC";
        $item->image = "dong-ho-nam-obaku-v132xcimc-1-org.jpg";
        $item->price = "3512000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Ánh bạc sang trọng, thời thượng là sản phẩm của thương hiệu đồng hồ Obaku có xuất xứ từ Đan Mạch";
        $item->category_id = 10;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 48;
        $item->name = "Đồng hồ Nam Obaku V175GMCBMC";
        $item->image = "dong-ho-nam-obaku-v175gmcbmc-1-org.jpg";
        $item->price = "3872000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Ánh bạc sang trọng, thời thượng là sản phẩm của thương hiệu đồng hồ Obaku có xuất xứ từ Đan Mạch";
        $item->category_id = 10;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 49;
        $item->name = "Đồng hồ Nam Obaku V171GMCBMC";
        $item->image = "dong-ho-nam-obaku-v171gmcbmc-1-org.jpg";
        $item->price = "4240000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Ánh bạc sang trọng, thời thượng là sản phẩm của thương hiệu đồng hồ Obaku có xuất xứ từ Đan Mạch";
        $item->category_id = 10;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 50;
        $item->name = "Đồng hồ Nam Obaku V178GXCBMC";
        $item->image = "dong-ho-nam-obaku-v178gxcbmc-1-org.jpg";
        $item->price = "3512000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Ánh bạc sang trọng, thời thượng là sản phẩm của thương hiệu đồng hồ Obaku có xuất xứ từ Đan Mạch";
        $item->category_id = 10;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

        $item = new Product;
        $item->id = 51;
        $item->name = "Đồng hồ Nam Obaku V124GCBMC1";
        $item->image = "dong-ho-nam-obaku-v124gcbmc1-1-org.jpg";
        $item->price = "3328000";
        $item->quantity = 2;
        $item->status = "Còn hàng";
        $item->supplier = "IOP";
        $item->description = "Ánh bạc sang trọng, thời thượng là sản phẩm của thương hiệu đồng hồ Obaku có xuất xứ từ Đan Mạch";
        $item->category_id = 10;
        $item->created_at = date('Y-m-d H:i:s');
        $item->updated_at  = date('Y-m-d H:i:s');
        $item->save();

    }
}
    